# Generated by Django 4.2.1 on 2023-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobileNumber', models.BigIntegerField()),
                ('age', models.BigIntegerField()),
                ('height', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'User Details',
                'db_table': 'User',
            },
        ),
    ]
